# Generated by Django 5.0.6 on 2025-10-23 14:45

from django.db import migrations
from django.conf import settings

# Função que será executada para criar os perfis
def criar_perfis_para_usuarios_existentes(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Perfil = apps.get_model('APP', 'Perfil')

    # Pega todos os usuários que não têm um perfil associado
    usuarios_sem_perfil = User.objects.filter(perfil__isnull=True)

    # Cria um perfil para cada um deles
    for usuario in usuarios_sem_perfil:
        Perfil.objects.create(usuario=usuario)


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_perfil'), # Verifique se o nome do arquivo anterior está correto
    ]

    operations = [
        # Diz ao Django para rodar nossa função
        migrations.RunPython(criar_perfis_para_usuarios_existentes),
    ]