# Generated by Django 5.2.7 on 2026-07-15 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_criar_perfis_faltantes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo', models.CharField(help_text='Nome ou Placa do veículo', max_length=100)),
                ('destino', models.CharField(max_length=200)),
                ('motivo', models.TextField(help_text='Motivo da reserva')),
                ('data_retirada', models.DateField()),
                ('hora_retirada', models.TimeField()),
                ('data_devolucao', models.DateField()),
                ('hora_devolucao', models.TimeField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_retirada', 'hora_retirada'],
            },
        ),
        migrations.DeleteModel(
            name='Reuniao',
        ),
    ]
