# Generated by Django 5.2.7 on 2026-07-15 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_reservaveiculo_delete_reuniao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reservaveiculo',
            options={'ordering': ['data_retirada']},
        ),
        migrations.RemoveField(
            model_name='reservaveiculo',
            name='hora_devolucao',
        ),
        migrations.RemoveField(
            model_name='reservaveiculo',
            name='hora_retirada',
        ),
        migrations.AlterField(
            model_name='reservaveiculo',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.veiculo'),
        ),
    ]
